config/routes.rb
OCS::Application.routes.draw do
  match '/iaa_s/destroy', to: 'iaa_s#destroy', via: :delete
  match '/iaa_s/myfriend', to: 'iaa_s#myfriend', via: :get
  get "iaa_s/manage"
  get "iaa_s/start"
  get "iaa_s/run"
  get "iaa_s/create_image"
  get "iaa_s/stop"
  get "iaa_s/reboot"
  get "iaa_s/show"
  post "iaa_s/create"
  get '/users/edit' 
   
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :iaa_s
  match '/signup', to: 'users#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match '/displayallusers', to: 'users#displayallusers', via: :get
  match '/deltactest', to: 'users#deltactest', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

 root to: "users#home"

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  #attr_accessible :first_name, :last_name, :email
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
  
end

app/models/users.rb
class Users < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
include SessionsHelper
end

app/controllers/iaa_s_controller.rb
class IaaSController < ApplicationController
  
  def index
  end

  def edit
  end

  def show
  end

  def new
    @api_url = "http://localhost:3001/api"
    client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    @hwprofiles = client.hardware_profiles
  end

  def create
    @api_url = "http://localhost:3001/api"
    client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    @lparams = params[:deals]  
    @img_name = params[:iname]  
    inst = client.create_instance @img_name, :hwp_id => @lparams[:hwp]
    flash[:success] = "VM " + @img_name + "created successfully"
  end

  def update
  end

  def manage
    @api_url = "http://localhost:3001/api"
    client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    @instance = client.instance(params[:id])
    flash[:success] = "Image id " + params[:id]
  end
  
  def stop
    @api_url = "http://localhost:3001/api"
    client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    @instance = client.instance(params[:id])
    @instance =  @instance.stop! unless @instance.state == 'STOPPED'
    flash[:success] =  @instance.image_id + " stoped successfuly"
    @instance = client.instance(params[:id])
    render iaa_s_manage_path
  end

  def reboot
    @api_url = "http://localhost:3001/api"
    client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    @instance = client.instance(params[:id])
    @instance = @instance.reboot! unless @instance.state == 'STOPPED'
    flash[:success] = "Image id " + @instance.image_id+ " restarted successfuly"
    @instance = client.instance(params[:id])
    render iaa_s_manage_path
  end

  def start
    @api_url = "http://localhost:3001/api"
    client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    @instance = client.instance(params[:id])
    @instance = @instance.start! unless @instance.state == 'RUNNING'
    flash[:success] = @instance.image_id + " started successfuly"
    @instance = client.instance(params[:id])
    render iaa_s_manage_path
  end
  
  def run
    # @api_url = "http://localhost:3001/api"
    #client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    # instance = client.instance(params[:id])
    #instance.start!
    #flash[:success] = "Image id " + params[:id] + "started successfuly"
  end
  
  def create_image
  end
  
  def destroy
    @api_url = "http://localhost:3001/api"
    client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    instance = client.instance(params[:id])
    instance.destroy! 
    flash[:success] =  instance.image_id + " destroyed successfuly"
    #render 'index'
  end
  
  def myfriend
    @api_url = "http://localhost:3001/api"
    client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') 
    instance = client.instance(params[:id])
    instance.destroy! 
    flash[:success] =  instance.image_id + " destroyed successfuly"
    render 'index'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user = User.find_by_email(params[:session][:email])
  if user && user.authenticate(params[:session][:password])
    sign_in user
    redirect_back_or user
  else
    flash.now[:error] = 'Invalid email/password combination' # Not quite right!
    render 'new'
  end
end

def destroy
  sign_out
  redirect_to root_path
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :index, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy
  

  def deltactest
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end


  def displayallusers
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    #@user = User.new(params[:user])
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to OCCS!"
      redirect_to @user
    else
      render 'new'
    end
  end


  def edit
    #@user = User.find(params[:id])
  end

  def update
    #@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  private
  def signed_in_user
    unless signed_in?
      store_location
    redirect_to signin_path, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/iaa_s_helper.rb
module IaaSHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

def redirect_back_or(default)
  redirect_to(session[:return_to] || default)
  session.delete(:return_to)
end

def store_location
  session[:return_to] = request.fullpath
end

  
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for (user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatars/#{gravatar_id}.png?s=#{size}"
    # image_tag(gravatar_url, alt: (user.last_name + ":)"), class: "gravatar")
    image_tag(gravatar_url, alt: user.last_name, class: "gravatar")
            end
end

app/views/iaa_s/create.html.erb
<h1>Created New VM instance :) ;)</h1>
<%= link_to 'New Instance', :action => 'new', :controller =>'iaa_s' %>
<%= link_to 'View Instances', :action => 'index', :controller =>'iaa_s' %>

app/views/iaa_s/destroy.html.erb
<h1> VM instance Destroyed :) ;)</h1>
<%= link_to 'New Instance', :action => 'new', :controller =>'iaa_s' %>
<%= link_to 'View Instances', :action => 'index', :controller =>'iaa_s' %>

app/views/iaa_s/edit.html.erb
<h1>IaaS#edit</h1>
<p>Find me in app/views/iaa_s/edit.html.erb</p>

app/views/iaa_s/index.html.erb
<% provide(:title, 'Deltacloud Test') %>
<h1>VM Instancess</h1>
<% @api_url = "http://localhost:3001/api"%>   

<%client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') %>


<% @instances = client.instances %>

<h5> 
<table>
  <tr>
    <th>Instance Id </th>
    <th>Name</th>
    <th>State</th>
    <th>Hardware Profile</th>
    <th>Actions</th>
  </tr>
</h5>
 
<% @instances.each do |instance| %>
  <tr>
    <td><%= instance.image_id %></td>
    <td><%= instance.private_addresses %></td>
    <td><%= instance.state %></td>
    <td><%= instance.hardware_profile_id %></td>
    <td><%= instance.actions %></td>
    <td><%= link_to 'manage Vm', :action => 'manage', :controller =>'iaa_s', id: instance._id %> </td>
    </tr>
<% end %>
</table>
 
<br />

<%= link_to 'New Instance', :action => 'new', :controller =>'iaa_s' %>

app/views/iaa_s/manage.html.erb
<h1>Manage VM</h1>
<% @api_url = "http://localhost:3001/api"%>   
<% client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') %>

<div>
  <table>
    <h5>
      <tr>
	<th>Image Id </th>
	<th>private Address</th>
	<th>State</th>
	<th>Actions</th>
      </tr>
    </h5>
    <tr>
      <td><%= @instance.image_id %></td>
      <td><%= @instance.private_addresses %></td>
      <td><%= @instance.state %></td>
      
      <td>
	<table> 
	  <tr> 
	    <% @instance.actions.each do |vm_action| %>
	    <% myaction = vm_action %>
	    <% if (myaction.to_s == "destroy") then myaction = "myfriend" end %>
	    <td> <%= link_to vm_action, :action => myaction, :controller =>'iaa_s', id: @instance._id %>
	    </td>
	    <% end %> 
	  <tr> 
	</table>  
      </td>
    </tr>
    
  
</table>
</div>
<div>
<%= link_to 'New Instance ', :action => 'new', :controller =>'iaa_s' %>
<%= link_to 'View Instances', :action => 'index', :controller =>'iaa_s' %>
</div>

app/views/iaa_s/myfriend.html.erb
<h1> VM instance destroyed by my friend :) ;)</h1>
<%= link_to 'New Instance', :action => 'new', :controller =>'iaa_s' %>b
<%= link_to 'View Instances', :action => 'index', :controller =>'iaa_s' %>

app/views/iaa_s/new.html.erb
<h1>TO Create New VM instance</h1>

<% @api_url = "http://localhost:3001/api"%>   

<%client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') %>
<%@hwprofiles = client.hardware_profiles%>

<%= form_tag("create", :method=>"post") do %>

<p><b>all collection for selected</b></p>
<%= label_tag(:q, "Select Hardware Profile:") %>
<%= collection_select("deals",:hwp, @hwprofiles, :id, :name) %>
<%= label_tag(:q, "Select Hardware Profile:") %>
<%= text_field_tag(:iname, "Enter name of VM") %>

<%= submit_tag("Create Instance") %>
<% end %>


<%= link_to 'View Instance', :action => 'index', :controller =>'iaa_s' %>

app/views/iaa_s/reboot.html.erb
<h1> VM instance Restarted :) ;)</h1>
<%= link_to 'New Instance', :action => 'new', :controller =>'iaa_s' %>
<%= link_to 'View Instances', :action => 'index', :controller =>'iaa_s' %>

app/views/iaa_s/show.html.erb
<h1>IaaS#show</h1>
<p>Find me in app/views/iaa_s/show.html.erb</p>

app/views/iaa_s/start.html.erb
<h1> VM instance Started :) ;)</h1>
<%= link_to 'New Instance', :action => 'new', :controller =>'iaa_s' %>b
<%= link_to 'View Instances', :action => 'index', :controller =>'iaa_s' %>

app/views/iaa_s/stop.html.erb
<h1> VM instance Stopped :) ;)</h1>
<%= link_to 'New Instance', :action => 'new', :controller =>'iaa_s' %>
<%= link_to 'View Instances', :action => 'index', :controller =>'iaa_s' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "OCS ", root_path, id: "logo" %>
      <nav>
	<ul class="nav pull-right">
	  <li><%= link_to "Home", root_path %></li>

	  <% if signed_in? %>
	  <li><%= link_to "Users", users_path %></li>
	      <li><%= link_to "Sign Outer", signout_path, method: "delete" %></li>
<li><%= link_to "Settings", edit_user_path(current_user) %></li>

	  <li id="fat-menu" class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      Account <b class="caret"></b>
	    </a>
	    <ul class="dropdown-menu">
	      <li><%= link_to "Profile", current_user %></li>
	      <li><%= link_to "Settings", '#' %></li>
	      <li class="divider"></li>
	      <li>
		<%= link_to "Sign out", signout_path, method: "delete" %>
	      </li>
	    </ul>
	  </li>
	  <% else %>
	  <li><%= link_to "Sign in", signin_path %></li>
	  <% end %>
	</ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>OCS | <%= yield(:title) %></title>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>


<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<div class="alert alert-error">
The form contains <%= pluralize(@user.errors.count, "error") %>.
</div>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li>* <%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/users/_user.html.erb
 <li>
    <%= gravatar_for user, size: 52 %>
    <%= link_to (user.first_name + " " + user.last_name), user %>
    <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, confirm: "Are you sure?" %>
    <% end %>

  </li>

app/views/users/deltactest.html.erb
<% provide(:title, 'Deltacloud Test') %>
<h1>A Deltacloud Tester</h1>
<% @api_url = "http://localhost:3001/api"%>   

<%client = Deltacloud::Client(@api_url, 'mockuser', 'mockpassword') %>

<h3>These are the realms <%= @realm = client.realms %></h3>


<% @instances = client.instances %>

<h5> 
<table>
  <tr>
    <th>Instance Id </th>
    <th>Name</th>
    <th>State</th>
    <th>Hardware Profile</th>
    <th>Actions</th>
  </tr>
 
<% @instances.each do |instance| %>
  <tr>
    <td><%= instance.image_id %></td>
    <td><%= instance.private_addresses %></td>
    <td><%= instance.state %></td>
    <td><%= instance.hardware_profile_id %></td>
    <td><%= instance.actions %></td>
    </tr>
<% end %>
</table>
 
<br />
</h5>

app/views/users/displayallusers.html.erb
<div class="row">
<aside class="span4">
<section>
<h1>
</h1>
<% @user.each do |user| %>
<div><%=  (user.first_name + "   " + user.last_name + "  : " +user.email) %>
</div>
<% end %>

</section>
</aside>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/home.html.erb
<div class="center hero-unit">
<h1>Welcome to OCS App</h1>
<h2>
Nothing Special
</h2>
<%= link_to "Sign up now!", "/signup", class: "btn btn-large btn-primary" %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
  <%= render user %>
  <% end %>
  
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
<div class="span6 offset3">
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>
<%= f.label :last_name %>
<%= f.text_field :last_name %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name + @user.last_name ) %>
<div class="row">
<aside class="span4">
<section>
<h1>
<%= gravatar_for @user %>
<%=  (@user.first_name + "   " + @user.last_name)  %>


</h1>
</section>
</aside>
</div>